version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/honey_hotel_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_MAIL_USERNAME=${EMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_MUI_X_LICENSEKEY=${REACT_APP_MUI_X_LICENSEKEY}
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: honey_hotel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
